### ISSUE TITLE
report: Generate aggregate call graph in JavaScript in the browser instead of with graphviz

### ISSUE THREAD

**Issue by rbalint** [firebuild/firebuild#1289]
Firebuild depends on the external `dot` (Graphviz) binary to create the aggregate call graph when generating the build report.

In a CI run this requires the extra graphviz package to be installed, which a bit less user friendly than probably needs to be.

A few links to explore:
https://stackoverflow.com/questions/6344318/pure-javascript-graphviz-equivalent
https://codesandbox.io/examples/package/d3-graphviz
https://observablehq.com/@anpaz/d3-dag

**Comment by rbalint** [comment]
Also: https://cdnjs.com/libraries/d3-graphviz

**Comment by basilgello** [comment]
@rbalint Check your mailbox please!
