### ISSUE TITLE
Clean up partial symlink support

### ISSUE THREAD

**Issue by egmontkob-work** [firebuild/firebuild#784]
We're not yet planning to add proper symlink support. Instead, we just track if a process does something related, and disable shortcutting in that case. We only allow transparently following a symlink, and that's all.

To complete this picture:

- We disable shortcutting if a `symlink()` succeeded, but not if it failed. Failure should also be handled (i.e. disable shortcutting). Maybe move this out from `Process::handle_symlink()` to `proc_ic_msg()`'s `case FBBCOMM_TAG_symlink`, like we do with hardlinks.

- We don't do anything on `readlink()`, we need to disable shortcutting.

- We handle `lstat()` equivalently to `stat()` which is not good. For `lstat()`:

  - Can we simply disable shortcutting? Or would that affect too many processes?

  - Or do we need to do something more fine-grained? Like this:

    - If `lstat()` failed: `stat()` would also fail, can we register it like that? The problem is: when we match whether we can replay, a dangling symlink would still match and we'd incorrectly try to shortcut something that we shouldn't.

    - If `lstat()` returned a regular file or directory: `stat()` would also return that, can we register it like that? Sounds okay to me.
 
    - If `lstat()` returned a symlink: We can't handle that, need to disable shortcutting.

**Comment by rbalint** [comment]
The partial "cleanup" has been reverted. The plan is proceeding towards fully supporting symlinks.
