### ISSUE TITLE
Jobserver handling improvements

### ISSUE THREAD

**Issue by egmontkob-work** [firebuild/firebuild#821]
Followup of #750's review:

Problem:

`make` might act as a jobserver, in that case it sets the env var `MAKEFLAGS` to contain the substring `--jobserver-fds=R,W` or `--jobserver-auth=R,W` (which??). Jobserver-aware children use this for improved parallelism.

However, the child is perhaps not aware of make's jobserver feature at all, doesn't look at it this env var and doesn't remove it either, and manipulates the fds. For example, it closes them and then opens something else to the same numbers. Then it launches yet another child. There the env variable describes the jobserver situation incorrectly.

A notable example of this is `./configure` with all its shell script and endless redirection magic. In particular, if a part of `./configure` would test a jobserver-supporting tool, it might easily fail.

On the other hand, there could be sub-jobservers, and their own fds may or may not be the same as the parent jobserver's. If we cannot distinguish these from `./configure`-like jobserver-unaware tools then all we can do is some more-or-less fragile heuristics (as #750 is doing something that looks reasonably good for now).

What happens in case of misdetection:

Incorrectly assuming that a pipe belongs to a jobserver, where in fact it doesn't, might result in faulty replaying behavior (we ignore traffic that we should take into account).

Failing to recognize that a pipe belongs to a jobserver, where in fact it does, results in subpar performance, shortcutting getting disabled.

Suggested solution 1:

In the config file, maintain a list of programs that are known to be able to act like a jobserver.

If such a program (or a `fork()` thereof -- obviously it still counts as the same program) `exec()`s something and has the `MAKEFLAGS` env var set, then mark the corresponding `FileFD` entries in `fds_` as belonging to a jobserver. (For robustness, here we might add additional checks that the given fds indeed have to exist and have to be pipes with the proper read/write direction.)

During `fork()`, `dup()`, `close()` and similar operations, as well as across `exec()`s where the old process isn't on our aforementioned list, we'd let our current traciking of `FileFD` carry the jobserver property as it already carries any other property, i.e. we'd assume that whether the underlying fd object (and not the number it belongs to) keeps its jobserver-fd or non-jobserver-fd property.

Suggested solution 2:

Try to do this detection automatically. We allow and honour the jobserver values if they appeared newly, i.e. weren't present in the parent process's environment. Similarly, allow and honour them if they were changed. In these cases we can safely assume that the parent process acts as a jobserver, and the numbers seen in the environment are in fact valid jobserver fds numbers.

This is sort of an automatically maintained list, as opposed to the manually maintained list of solution 1. The advantage is that we don't have to maintain that list. The drawback is that if a sub-jobserver happens to reuse the same fds that it received from its parent then that wouldn't be recognized as a jobserver.

I'm wondering: Do sub-jobservers keep their jobserver connection towards the parent jobserver? I pretty much assume so, but we should check a real life example. In that case it's extremely unlikely that the sub-jobserver would reuse the same fd numbers, since it would deliberately need to move the parent fds away to some other numbers, I see no reason why any of them would do so. So, if we look for the jobserver fd numbers changing in the environment, I hope that we catch practically every sub-jobserver.

We could also have both solution in place together.

**Comment by rbalint** [comment]
Not just `make`, but Rust's `cargo` and `rustc` also use jobserver:
` "CARGO_MAKEFLAGS=-j --jobserver-fds=7,8 --jobserver-auth=7,8"`

Not ignoring `rustc`'s jobserver usage prevents shortcutting parallel Rust builds. Running Rust builds with `-j1` disables jobserver usage, but that's useful for testing only because most firebuild users would most likely want parallel Rust builds and `cargo`'s jobserver can't be disabled: https://github.com/rust-lang/cargo/issues/4721

**Comment by rbalint** [comment]
I went with solution 1, with a twist. the config file lists the commands _honoring_ the jobserver environment variable. This makes detection cheaper and if the jobserver fds are messed up the listed commands would fail anyway.
